"""empty message

Revision ID: 0963a4bc648e
Revises: 5bd153f563f7
Create Date: 2018-06-05 15:51:04.929000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0963a4bc648e'
down_revision = '5bd153f563f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('userId', sa.String(length=255), nullable=False))
    op.add_column('collect', sa.Column('userId', sa.String(length=255), nullable=False))
    op.add_column('order', sa.Column('userId', sa.String(length=255), nullable=False))
    op.add_column('usercoupon', sa.Column('userId', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercoupon', 'userId')
    op.drop_column('order', 'userId')
    op.drop_column('collect', 'userId')
    op.drop_column('cart', 'userId')
    # ### end Alembic commands ###
