"""empty message

Revision ID: 1d6820da391b
Revises: 4467254a96f1
Create Date: 2018-06-01 09:28:17.552000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6820da391b'
down_revision = '4467254a96f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creatTime', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'creatTime')
    # ### end Alembic commands ###
