"""empty message

Revision ID: 5bd153f563f7
Revises: 71c5dab583d2
Create Date: 2018-06-05 15:07:29.129000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd153f563f7'
down_revision = '71c5dab583d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('userId', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'userId')
    # ### end Alembic commands ###
