"""empty message

Revision ID: 71c5dab583d2
Revises: c4dad93bb808
Create Date: 2018-06-05 15:02:18.632000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c5dab583d2'
down_revision = 'c4dad93bb808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userId', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userId')
    # ### end Alembic commands ###
