"""empty message

Revision ID: 9cbe6f07dbe9
Revises: 6f6f8ee3f52c
Create Date: 2018-06-05 16:31:34.461000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cbe6f07dbe9'
down_revision = '6f6f8ee3f52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'cartId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cartId', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
