"""empty message

Revision ID: c4dad93bb808
Revises: 1d6820da391b
Create Date: 2018-06-01 10:01:25.440000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dad93bb808'
down_revision = '1d6820da391b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodsId', sa.String(length=255), nullable=False),
    sa.Column('goodsPrice', sa.String(length=255), nullable=False),
    sa.Column('goodsNumber', sa.String(length=255), nullable=False),
    sa.Column('goodsStyle', sa.String(length=255), nullable=False),
    sa.Column('goodsSize', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chosen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodsId', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodsId', sa.String(length=255), nullable=False),
    sa.Column('collectId', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couponId', sa.String(length=255), nullable=False),
    sa.Column('spendMoney', sa.String(length=255), nullable=False),
    sa.Column('disCount', sa.String(length=255), nullable=False),
    sa.Column('endTime', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodsId', sa.String(length=255), nullable=False),
    sa.Column('discount', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodsId', sa.String(length=255), nullable=False),
    sa.Column('goodsName', sa.String(length=255), nullable=False),
    sa.Column('goodsImgArr', sa.Text(), nullable=False),
    sa.Column('goodsPrice', sa.String(length=255), nullable=False),
    sa.Column('TopCategoryId', sa.String(length=255), nullable=False),
    sa.Column('SecondaryCategoryId', sa.Integer(), nullable=False),
    sa.Column('ThirdCategoryId', sa.String(length=255), nullable=False),
    sa.Column('goodsSize', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.String(length=255), nullable=False),
    sa.Column('orderType', sa.String(length=255), nullable=False),
    sa.Column('goodsId', sa.String(length=255), nullable=False),
    sa.Column('addressId', sa.String(length=255), nullable=False),
    sa.Column('goodsNumber', sa.String(length=255), nullable=False),
    sa.Column('goodsStyle', sa.String(length=255), nullable=False),
    sa.Column('goodsSize', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('createTime', sa.String(length=255), nullable=False),
    sa.Column('orderNo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usercoupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couponId', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercoupon')
    op.drop_table('order')
    op.drop_table('goods')
    op.drop_table('discount')
    op.drop_table('coupon')
    op.drop_table('collect')
    op.drop_table('chosen')
    op.drop_table('cart')
    # ### end Alembic commands ###
